"""Change schema to match frontend naming convention

Revision ID: 21d3015a8959
Revises: 5c62cf176efa
Create Date: 2024-06-16 02:33:12.989204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d3015a8959'
down_revision: Union[str, None] = '5c62cf176efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('schoolName', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('countryName', sa.String(), nullable=True))
    op.add_column('institutions', sa.Column('paymentType', sa.String(), nullable=True))
    op.drop_index('ix_institutions_country_name', table_name='institutions')
    op.drop_index('ix_institutions_school_name', table_name='institutions')
    op.create_index(op.f('ix_institutions_countryName'), 'institutions', ['countryName'], unique=False)
    op.create_index(op.f('ix_institutions_schoolName'), 'institutions', ['schoolName'], unique=False)
    op.drop_column('institutions', 'country_name')
    op.drop_column('institutions', 'school_name')
    op.drop_column('institutions', 'payment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('payment_type', sa.VARCHAR(), nullable=True))
    op.add_column('institutions', sa.Column('school_name', sa.VARCHAR(), nullable=True))
    op.add_column('institutions', sa.Column('country_name', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_institutions_schoolName'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_countryName'), table_name='institutions')
    op.create_index('ix_institutions_school_name', 'institutions', ['school_name'], unique=False)
    op.create_index('ix_institutions_country_name', 'institutions', ['country_name'], unique=False)
    op.drop_column('institutions', 'paymentType')
    op.drop_column('institutions', 'countryName')
    op.drop_column('institutions', 'schoolName')
    # ### end Alembic commands ###
