"""Add contact_email to institutions

Revision ID: 861b4ea667e9
Revises: 21d3015a8959
Create Date: 2024-06-16 02:57:39.229623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861b4ea667e9'
down_revision: Union[str, None] = '21d3015a8959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('contactEmail', sa.String(), nullable=True))
    op.create_index(op.f('ix_institutions_address'), 'institutions', ['address'], unique=False)
    op.create_index(op.f('ix_institutions_contactEmail'), 'institutions', ['contactEmail'], unique=False)
    op.create_index(op.f('ix_institutions_paymentType'), 'institutions', ['paymentType'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutions_paymentType'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_contactEmail'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_address'), table_name='institutions')
    op.drop_column('institutions', 'contactEmail')
    # ### end Alembic commands ###
